name: speech_to_text
description: "Speech to Text."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_tts: ^4.2.3
  dropdown_button2: ^2.3.9
  waveform_fft: ^0.0.3
  fluttertoast: ^8.0.9


flutter:
  uses-material-design: true
